### ISSUE TITLE
Unexplainable/undocumented behaivour of API

### ISSUE THREAD

**Issue by azelk** [cfpb/ccdb5-api#102]
When you go to
https://cfpb.github.io/api/ccdb/api/index.html#/Complaints/get_
click "search consumer complaints", then "Try it out" and "Execute"

If you don't specify the format the response will be an html-page with js.
If you specify the format as json or csv it will never not load (hangs).

I get the same result with urllib library from python. The only workaround was to specify "?format=default" which is not documented

**Comment by sephcoster** [comment]
Thank you for this feedback @azelk. We're looking into this issue now and will keep you posted here as we make any required adjustments.

**Comment by sephcoster** [comment]
Hi @azelk. We have updated our API so that default queries return structured data rather than the Django REST Framework HTML default you were seeing before. Further, we updated our size=0 detection to avoid errors / issues ( #115 )

If you continue to run into issues please let us know. I believe this closes this issue. Thanks again for the report. 👍
