### ISSUE TITLE
Question about size parameter

### ISSUE THREAD

**Issue by joseandresmontes** [cfpb/ccdb5-api#133]
The following GET call returns a response with 100 entries as oppose to the requested 150. It seems that any size parameter above 100 is limited to the first 100 entries. 

Not sure if a feature or a bug but believe that any meaningful analysis would require more entries.

```
https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/?size=150&no_aggs=true
```

R chunck:
```r
url <- 'https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/'
query_params <- list(size = 150, no_aggs = 'true')

response <- GET(url=url, query = query_params)

content <- jsonlite::fromJSON(httr::content(response, "text", encoding = 'UTF-8'))
```

My goal is to create an R API Client package for the complaint database and this issue limits most of its functionality. 

Full API client package implementation can be found https://github.com/joseandresmontes/cfpbR

**Comment by sephcoster** [comment]
Hi @joseandresmontes - apologies for the delay in our reply.

On July 21st, we raised the API size call limit from 100 to 1000 to help accommodate a larger export using a raw API call that was not an export. (https://github.com/cfpb/ccdb5-api/pull/160)

Does this get you what you need for the API Client package, or were you looking for a much larger chunk size?

Thanks for looking at this and putting the package together!

**Comment by joseandresmontes** [comment]
Hello @sephcoster thanks for the reply and I think a larger chuck would be helpful if possible! According to the website, I see there are a total of 1,811,636 complaints, so hoping to be able to pull more than just 1,000 if possible. Particularly because each year seems to be getting more complaints so even doing a one-year study would hit the limit. I know there might be constraints but think it would be helpful for the community at large who do not want to export the whole dataset for a one year study.

**Comment by sephcoster** [comment]
Thanks for that feedback. Since streaming that many records can often take awhile, I think you might be better off specifying a format for the data to return (this is what we use for our export feature) which should return any number of records you require up to the full dataset (which we generate nightly and .zip for faster downloads).

To generate an example, try selecting the previous year (or week, or month) worth of data, then click "Export" you will get a link for CSV or JSON (pick your preference) that will download that entire year's complaint data. A year is a large file and takes awhile, but should return the data for the same queries at the size you need? That URL is `curl`-able and should be accessible programatically.

The key parameters there are the `format` (CSV or JSON) and `size` parameters which determine how many records get returned. Obviously your filter criteria are also important to have in there to return what you expect.

![Screen Shot 2020-10-28 at 2 33 35 PM](https://user-images.githubusercontent.com/1028659/97481782-aeb02680-192b-11eb-8d85-52288d29e7de.png)

Let me know if that gets you what you need?

**Comment by sephcoster** [comment]
Closing this for now, but happy to re-open if the above doesn't work for you. Thanks!
