### ISSUE TITLE
Trends API seems redirects to CFPB website 

### ISSUE THREAD

**Issue by gweissman86** [cfpb/ccdb5-api#158]
The Trends API seems broken.

Using the following code: curl -X GET "https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/trends?lens=overview&trend_interval=yearly" -H "accept: application/json"

The URL redirectS to the site https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/trends?dataLens=Overview&dataNormalization=None&dateInterval=Month&dateRange=3y&date_received_max=2020-07-15&date_received_min=2017-07-15&from=0&page=1&searchField=all&size=25&sort=created_date_desc&tab=Map

And if used in command line, curl returns the page HTML, rather than anything useful.

Other APIs don't seem to give the same problem.

**Comment by JeffreyMFarley** [comment]
It should work after 11 AM EDT today

https://www.consumerfinance.gov/about-us/events/consumer-response-trends-capability-tool-launch-demo/

**Comment by sephcoster** [comment]
Indeed, the API was recently launched last week. The API documentation went live a bit ahead of the launch. 

If you have any further questions please let us know (Github issues are a good spot for that). One note: your API URL indicated to us that our trend_interval documentation did not match production. We have updated the documentation accordingly via this pull request: https://github.com/cfpb/ccdb5-api/pull/159

Since this should be resolved I'll close this issue. Thank you for the inquiry!
