### ISSUE TITLE
Support credit card 

### ISSUE THREAD

**Issue by Awnisaeed** [cfpb/ccdb5-api#188]

**Comment by Ritajeanthomp63** [comment]
I don't know if I'm doing this correctly or not. I hope I am because it's very confusing. And I need help. So I clicked on an email for self Financial and read what it was about and then I called them to talk to them and have them explain it to me better. Well I decided I didn't want it and somehow they took $100 out of my account when I did not authorize it and so what I did was called them told them that I did not authorize that and I wanted my money back while they wouldn't so what I did was spent my $100 and then I told them several times I canceled this and they are continually charging me late fees and everything when they haven't even notified me through mail or email of any type of payment. And so now they're wanting me to pay them like $75 and it keeps going up and up and up. Thank you for your help and my name is Rita Thompson. 563-271-12220 is my phone number thank you have a wonderful evening
