### ISSUE TITLE
Undocumented server response on GET / search consumer complaints

### ISSUE THREAD

**Issue by khurd1** [cfpb/ccdb5-api#98]
Receiving undocumented response (TypeError: Failed to fetch)
![Screen Shot 2019-12-17 at 11 05 43 AM](https://user-images.githubusercontent.com/29287700/71012621-62fee080-20bd-11ea-8bfd-0babcac133dd.png)

**Comment by sephcoster** [comment]
Are you still receiving this response for that query? When I performed a similar search using the API documentation I am receiving a 200, but with the Django REST Framework page content instead of the JSON requested. We are investigating this and your failure to fetch issue from an hour ago.

In the interim, depending on your use case and what you are seeing now, I would recommend adding a "size" parameter to get the first N results, or - if you are looking to obtain an export - setting a "format" value. This should return results in the format requested in-line with the API documents. Please let me know if you're seeing a different outcome and/or if a specific use case is causing problems so we can investigate further? Thanks!

**Comment by khurd1** [comment]
Hi Seph,

Thanks so much for your quick reply! Adding a size param worked for me, so I will use that in the interim.

Thanks!



[cid:3142751d-06e4-4a0d-9e52-fe8193b0f42b]
Kate Ness
Product Manager
SilverCloud, Inc.
a:      135 Commerce Way, Portsmouth, NH 03801
w:      www.silvercloudinc.com<http://www.silvercloudinc.com/>
e:      kness@silvercloudinc.com<mailto:khurd@silvercloudinc.com>
[http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/facebook_sig.png]<https://www.facebook.com/silvercloudinc/>  [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/twitter_sig.png] <https://twitter.com/silvercloudinc>   [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/linkedin_sig.png] <https://www.linkedin.com/company/silvercloud-inc->

________________________________

**Comment by AdamZarger** [comment]
Hi @khurd1, this issue has been resolved in PR #106 and you no longer need to specify `size=0`
